export const inboxList = [
  {
    id: "1",
    subject: "Status Update",
    preview: "Meeting starts at 10 AM.",
    sender: "John Doe",
    date: "2025-04-05 07:55",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "2",
    subject: "FastVisa Support",
    preview: "Sure thing, Claren.",
    sender: "Ali Khan",
    date: "2025-04-05 07:50",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "3",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Please review the latest document.",
    sender: "Sara Lee",
    date: "2025-04-05 07:45",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "4",
    subject: "FastVisa Support",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Mary Hilda",
    date: "2025-04-05 07:40",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "5",
    subject: "Status Update",
    preview: "Don't forget the deadline.",
    sender: "Liam Patel",
    date: "2025-04-05 07:35",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "6",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Let\u2019s catch up soon!",
    sender: "Mary Hilda",
    date: "2025-04-05 07:30",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "7",
    subject: "Document Review",
    preview: "The file has been sent.",
    sender: "Obaidullah",
    date: "2025-04-05 07:25",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "8",
    subject: "Profile Update",
    preview: "Your profile is incomplete.",
    sender: "Sara Lee",
    date: "2025-04-05 07:20",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "9",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Let\u2019s catch up soon!",
    sender: "Sara Lee",
    date: "2025-04-05 07:15",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "10",
    subject: "Document Review",
    preview: "Your case has been updated.",
    sender: "Sara Lee",
    date: "2025-04-05 07:10",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "11",
    subject: "Meeting Reminder",
    preview: "Your case has been updated.",
    sender: "John Doe",
    date: "2025-04-05 07:05",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "12",
    subject: "Document Review",
    preview: "Meeting starts at 10 AM.",
    sender: "Mary Hilda",
    date: "2025-04-05 07:00",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "13",
    subject: "FastVisa Support",
    preview: "Please review the latest document.",
    sender: "Liam Patel",
    date: "2025-04-05 06:55",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "14",
    subject: "Meeting Reminder",
    preview: "Meeting starts at 10 AM.",
    sender: "Jane Smith",
    date: "2025-04-05 06:50",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "15",
    subject: "Status Update",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Sara Lee",
    date: "2025-04-05 06:45",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "16",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Let\u2019s catch up soon!",
    sender: "Ali Khan",
    date: "2025-04-05 06:40",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "17",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Welcome aboard!",
    sender: "Liam Patel",
    date: "2025-04-05 06:35",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "18",
    subject: "Meeting Reminder",
    preview: "Let\u2019s catch up soon!",
    sender: "John Doe",
    date: "2025-04-05 06:30",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "19",
    subject: "Meeting Reminder",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Jane Smith",
    date: "2025-04-05 06:25",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "20",
    subject: "Meeting Reminder",
    preview: "Sure thing, Claren.",
    sender: "Sara Lee",
    date: "2025-04-05 06:20",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "21",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Liam Patel",
    date: "2025-04-05 06:15",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "22",
    subject: "Status Update",
    preview: "Sure thing, Claren.",
    sender: "Jane Smith",
    date: "2025-04-05 06:10",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "23",
    subject: "Profile Update",
    preview: "Your profile is incomplete.",
    sender: "Mary Hilda",
    date: "2025-04-05 06:05",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "24",
    subject: "Profile Update",
    preview: "Meeting starts at 10 AM.",
    sender: "Jane Smith",
    date: "2025-04-05 06:00",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "25",
    subject: "Meeting Reminder",
    preview: "Sure thing, Claren.",
    sender: "John Doe",
    date: "2025-04-05 05:55",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "26",
    subject: "Document Review",
    preview: "Sure thing, Claren.",
    sender: "Michael Chen",
    date: "2025-04-05 05:50",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "27",
    subject: "Meeting Reminder",
    preview: "Meeting starts at 10 AM.",
    sender: "Liam Patel",
    date: "2025-04-05 05:45",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "28",
    subject: "Status Update",
    preview: "The file has been sent.",
    sender: "Ali Khan",
    date: "2025-04-05 05:40",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "29",
    subject: "Status Update",
    preview: "Please review the latest document.",
    sender: "John Doe",
    date: "2025-04-05 05:35",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "30",
    subject: "Profile Update",
    preview: "Meeting starts at 10 AM.",
    sender: "Sara Lee",
    date: "2025-04-05 05:30",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "31",
    subject: "Profile Update",
    preview: "Welcome aboard!",
    sender: "Michael Chen",
    date: "2025-04-05 05:25",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "32",
    subject: "FastVisa Support",
    preview: "Welcome aboard!",
    sender: "Ali Khan",
    date: "2025-04-05 05:20",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "33",
    subject: "FastVisa Support",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Michael Chen",
    date: "2025-04-05 05:15",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "34",
    subject: "FastVisa Support",
    preview: "Meeting starts at 10 AM.",
    sender: "Sara Lee",
    date: "2025-04-05 05:10",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "35",
    subject: "Meeting Reminder",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Obaidullah",
    date: "2025-04-05 05:05",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "36",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Sure thing, Claren.",
    sender: "Mary Hilda",
    date: "2025-04-05 05:00",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "37",
    subject: "Profile Update",
    preview: "Welcome aboard!",
    sender: "Sara Lee",
    date: "2025-04-05 04:55",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "38",
    subject: "Document Review",
    preview: "Your profile is incomplete.",
    sender: "Liam Patel",
    date: "2025-04-05 04:50",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "39",
    subject: "Profile Update",
    preview: "Don't forget the deadline.",
    sender: "Liam Patel",
    date: "2025-04-05 04:45",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "40",
    subject: "Meeting Reminder",
    preview: "Let\u2019s catch up soon!",
    sender: "Michael Chen",
    date: "2025-04-05 04:40",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "41",
    subject: "Document Review",
    preview: "The file has been sent.",
    sender: "Jane Smith",
    date: "2025-04-05 04:35",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "42",
    subject: "Profile Update",
    preview: "Meeting starts at 10 AM.",
    sender: "Claren",
    date: "2025-04-05 04:30",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "43",
    subject: "Status Update",
    preview: "The file has been sent.",
    sender: "FastVisa Support",
    date: "2025-04-05 04:25",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "44",
    subject: "Meeting Reminder",
    preview: "Your profile is incomplete.",
    sender: "John Doe",
    date: "2025-04-05 04:20",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "45",
    subject: "Profile Update",
    preview: "Your case has been updated.",
    sender: "Mary Hilda",
    date: "2025-04-05 04:15",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "46",
    subject: "Profile Update",
    preview: "Your case has been updated.",
    sender: "Sara Lee",
    date: "2025-04-05 04:10",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "47",
    subject: "Status Update",
    preview: "Don't forget the deadline.",
    sender: "Mary Hilda",
    date: "2025-04-05 04:05",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "48",
    subject: "Document Review",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Liam Patel",
    date: "2025-04-05 04:00",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "49",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Don't forget the deadline.",
    sender: "Michael Chen",
    date: "2025-04-05 03:55",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "50",
    subject: "FastVisa Support",
    preview: "Your case has been updated.",
    sender: "Sara Lee",
    date: "2025-04-05 03:50",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "51",
    subject: "FastVisa Support",
    preview: "Your case has been updated.",
    sender: "Obaidullah",
    date: "2025-04-05 03:45",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "52",
    subject: "Profile Update",
    preview: "The file has been sent.",
    sender: "Jane Smith",
    date: "2025-04-05 03:40",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "53",
    subject: "Profile Update",
    preview: "Sure thing, Claren.",
    sender: "FastVisa Support",
    date: "2025-04-05 03:35",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "54",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Welcome aboard!",
    sender: "Ali Khan",
    date: "2025-04-05 03:30",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "55",
    subject: "FastVisa Support",
    preview: "Meeting starts at 10 AM.",
    sender: "Michael Chen",
    date: "2025-04-05 03:25",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "56",
    subject: "FastVisa Support",
    preview: "The file has been sent.",
    sender: "Michael Chen",
    date: "2025-04-05 03:20",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "57",
    subject: "Profile Update",
    preview: "Let\u2019s catch up soon!",
    sender: "Claren",
    date: "2025-04-05 03:15",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "58",
    subject: "Meeting Reminder",
    preview: "Sure thing, Claren.",
    sender: "Sara Lee",
    date: "2025-04-05 03:10",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "59",
    subject: "Meeting Reminder",
    preview: "Please review the latest document.",
    sender: "Obaidullah",
    date: "2025-04-05 03:05",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "60",
    subject: "Meeting Reminder",
    preview: "Please review the latest document.",
    sender: "Jane Smith",
    date: "2025-04-05 03:00",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "61",
    subject: "Document Review",
    preview: "Sure thing, Claren.",
    sender: "Ali Khan",
    date: "2025-04-05 02:55",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "62",
    subject: "FastVisa Support",
    preview: "Please review the latest document.",
    sender: "Michael Chen",
    date: "2025-04-05 02:50",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "63",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Please review the latest document.",
    sender: "Sara Lee",
    date: "2025-04-05 02:45",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "64",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Let\u2019s catch up soon!",
    sender: "Obaidullah",
    date: "2025-04-05 02:40",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "65",
    subject: "Document Review",
    preview: "The file has been sent.",
    sender: "Mary Hilda",
    date: "2025-04-05 02:35",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "66",
    subject: "Profile Update",
    preview: "Welcome aboard!",
    sender: "Sara Lee",
    date: "2025-04-05 02:30",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "67",
    subject: "Profile Update",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Michael Chen",
    date: "2025-04-05 02:25",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "68",
    subject: "Status Update",
    preview: "Welcome aboard!",
    sender: "Sara Lee",
    date: "2025-04-05 02:20",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "69",
    subject: "FastVisa Support",
    preview: "The file has been sent.",
    sender: "FastVisa Support",
    date: "2025-04-05 02:15",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "70",
    subject: "Profile Update",
    preview: "Your profile is incomplete.",
    sender: "Sara Lee",
    date: "2025-04-05 02:10",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "71",
    subject: "Profile Update",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Mary Hilda",
    date: "2025-04-05 02:05",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "72",
    subject: "Document Review",
    preview: "Meeting starts at 10 AM.",
    sender: "FastVisa Support",
    date: "2025-04-05 02:00",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "73",
    subject: "Document Review",
    preview: "Let\u2019s catch up soon!",
    sender: "Obaidullah",
    date: "2025-04-05 01:55",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "74",
    subject: "Status Update",
    preview: "Your case has been updated.",
    sender: "FastVisa Support",
    date: "2025-04-05 01:50",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "75",
    subject: "Meeting Reminder",
    preview: "The file has been sent.",
    sender: "Ali Khan",
    date: "2025-04-05 01:45",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "76",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Don't forget the deadline.",
    sender: "Jane Smith",
    date: "2025-04-05 01:40",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "77",
    subject: "Profile Update",
    preview: "Meeting starts at 10 AM.",
    sender: "John Doe",
    date: "2025-04-05 01:35",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "78",
    subject: "Document Review",
    preview: "Welcome aboard!",
    sender: "Obaidullah",
    date: "2025-04-05 01:30",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "79",
    subject: "FastVisa Support",
    preview: "Let\u2019s catch up soon!",
    sender: "Obaidullah",
    date: "2025-04-05 01:25",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "80",
    subject: "FastVisa Support",
    preview: "The file has been sent.",
    sender: "Sara Lee",
    date: "2025-04-05 01:20",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "81",
    subject: "Profile Update",
    preview: "The file has been sent.",
    sender: "Claren",
    date: "2025-04-05 01:15",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "82",
    subject: "Document Review",
    preview: "Meeting starts at 10 AM.",
    sender: "Sara Lee",
    date: "2025-04-05 01:10",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "83",
    subject: "Meeting Reminder",
    preview: "Please review the latest document.",
    sender: "Jane Smith",
    date: "2025-04-05 01:05",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "84",
    subject: "Status Update",
    preview: "Welcome aboard!",
    sender: "Mary Hilda",
    date: "2025-04-05 01:00",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "85",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Welcome aboard!",
    sender: "Michael Chen",
    date: "2025-04-05 00:55",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "86",
    subject: "Document Review",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Ali Khan",
    date: "2025-04-05 00:50",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "87",
    subject: "FastVisa Support",
    preview: "The file has been sent.",
    sender: "Mary Hilda",
    date: "2025-04-05 00:45",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "88",
    subject: "FastVisa Support",
    preview: "Your case has been updated.",
    sender: "John Doe",
    date: "2025-04-05 00:40",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "89",
    subject: "Status Update",
    preview: "Sure thing, Claren.",
    sender: "Claren",
    date: "2025-04-05 00:35",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "90",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Welcome aboard!",
    sender: "Claren",
    date: "2025-04-05 00:30",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "91",
    subject: "Profile Update",
    preview: "Your case has been updated.",
    sender: "Sara Lee",
    date: "2025-04-05 00:25",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "92",
    subject: "FastVisa Support",
    preview: "Please review the latest document.",
    sender: "Obaidullah",
    date: "2025-04-05 00:20",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "93",
    subject: "Document Review",
    preview: "Welcome aboard!",
    sender: "Claren",
    date: "2025-04-05 00:15",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "94",
    subject: "Profile Update",
    preview: "Let\u2019s catch up soon!",
    sender: "Jane Smith",
    date: "2025-04-05 00:10",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "95",
    subject: "Meeting Reminder",
    preview: "Please review the latest document.",
    sender: "Claren",
    date: "2025-04-05 00:05",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "96",
    subject: "Meeting Reminder",
    preview: "Sure thing, Claren.",
    sender: "Michael Chen",
    date: "2025-04-05 00:00",
    isGroup: true,
    isUnread: true,
  },
  {
    id: "97",
    subject: "I-589 - AMARKHIL, Obaidullah",
    preview: "Meeting starts at 10 AM.",
    sender: "Sara Lee",
    date: "2025-04-04 23:55",
    isGroup: true,
    isUnread: false,
  },
  {
    id: "98",
    subject: "Status Update",
    preview: "Don't forget the deadline.",
    sender: "Liam Patel",
    date: "2025-04-04 23:50",
    isGroup: false,
    isUnread: false,
  },
  {
    id: "99",
    subject: "Status Update",
    preview: "Hey there! Welcome to your inbox.",
    sender: "Liam Patel",
    date: "2025-04-04 23:45",
    isGroup: false,
    isUnread: true,
  },
  {
    id: "100",
    subject: "Document Review",
    preview: "Welcome aboard!",
    sender: "Liam Patel",
    date: "2025-04-04 23:40",
    isGroup: false,
    isUnread: false,
  },
];

export const messages: Record<
  string,
  Array<{
    id: string;
    chatId: string;
    sender: string;
    text: string;
    time: string;
    date: string;
  }>
> = {
  "1": [
    {
      id: "1",
      chatId: "1",
      sender: "FastVisa Support",
      text: "The file has been sent.",
      time: "03:54",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "1",
      sender: "John Doe",
      text: "Your case has been updated.",
      time: "04:18",
      date: "2025-04-05",
    },
  ],
  "2": [
    {
      id: "1",
      chatId: "2",
      sender: "Liam Patel",
      text: "Please review the latest document.",
      time: "03:07",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "2",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "03:25",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "2",
      sender: "Ali Khan",
      text: "Your profile is incomplete.",
      time: "03:20",
      date: "2025-04-05",
    },
  ],
  "3": [
    {
      id: "1",
      chatId: "3",
      sender: "Mary Hilda",
      text: "Let\u2019s catch up soon!",
      time: "07:51",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "3",
      sender: "Liam Patel",
      text: "Your case has been updated.",
      time: "03:13",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "3",
      sender: "FastVisa Support",
      text: "The file has been sent.",
      time: "07:12",
      date: "2025-04-05",
    },
  ],
  "4": [
    {
      id: "1",
      chatId: "4",
      sender: "Mary Hilda",
      text: "Meeting starts at 10 AM.",
      time: "03:36",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "4",
      sender: "Obaidullah",
      text: "Your profile is incomplete.",
      time: "06:37",
      date: "2025-04-05",
    },
  ],
  "5": [
    {
      id: "1",
      chatId: "5",
      sender: "John Doe",
      text: "The file has been sent.",
      time: "07:15",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "5",
      sender: "Mary Hilda",
      text: "Don't forget the deadline.",
      time: "03:28",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "5",
      sender: "Mary Hilda",
      text: "Your case has been updated.",
      time: "07:20",
      date: "2025-04-05",
    },
  ],
  "6": [
    {
      id: "1",
      chatId: "6",
      sender: "FastVisa Support",
      text: "Meeting starts at 10 AM.",
      time: "06:42",
      date: "2025-04-05",
    },
  ],
  "7": [
    {
      id: "1",
      chatId: "7",
      sender: "Claren",
      text: "Hey there! Welcome to your inbox.",
      time: "07:54",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "7",
      sender: "Liam Patel",
      text: "Welcome aboard!",
      time: "07:48",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "7",
      sender: "FastVisa Support",
      text: "Don't forget the deadline.",
      time: "07:59",
      date: "2025-04-05",
    },
  ],
  "8": [
    {
      id: "1",
      chatId: "8",
      sender: "Obaidullah",
      text: "Welcome aboard!",
      time: "03:15",
      date: "2025-04-05",
    },
  ],
  "9": [
    {
      id: "1",
      chatId: "9",
      sender: "Liam Patel",
      text: "Sure thing, Claren.",
      time: "07:13",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "9",
      sender: "Obaidullah",
      text: "The file has been sent.",
      time: "06:04",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "9",
      sender: "Sara Lee",
      text: "Hey there! Welcome to your inbox.",
      time: "07:55",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "9",
      sender: "Jane Smith",
      text: "Don't forget the deadline.",
      time: "04:17",
      date: "2025-04-05",
    },
  ],
  "10": [
    {
      id: "1",
      chatId: "10",
      sender: "Jane Smith",
      text: "Your case has been updated.",
      time: "03:26",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "10",
      sender: "Ali Khan",
      text: "Please review the latest document.",
      time: "06:19",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "10",
      sender: "Jane Smith",
      text: "Sure thing, Claren.",
      time: "05:49",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "10",
      sender: "John Doe",
      text: "Your case has been updated.",
      time: "03:14",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "10",
      sender: "Obaidullah",
      text: "Please review the latest document.",
      time: "06:07",
      date: "2025-04-05",
    },
  ],
  "11": [
    {
      id: "1",
      chatId: "11",
      sender: "Michael Chen",
      text: "Sure thing, Claren.",
      time: "03:19",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "11",
      sender: "Jane Smith",
      text: "Don't forget the deadline.",
      time: "06:45",
      date: "2025-04-05",
    },
  ],
  "12": [
    {
      id: "1",
      chatId: "12",
      sender: "FastVisa Support",
      text: "Meeting starts at 10 AM.",
      time: "03:55",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "12",
      sender: "Claren",
      text: "Meeting starts at 10 AM.",
      time: "06:17",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "12",
      sender: "Liam Patel",
      text: "Sure thing, Claren.",
      time: "03:02",
      date: "2025-04-05",
    },
  ],
  "13": [
    {
      id: "1",
      chatId: "13",
      sender: "Mary Hilda",
      text: "Hey there! Welcome to your inbox.",
      time: "03:19",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "13",
      sender: "Michael Chen",
      text: "Meeting starts at 10 AM.",
      time: "06:07",
      date: "2025-04-05",
    },
  ],
  "14": [
    {
      id: "1",
      chatId: "14",
      sender: "Claren",
      text: "Let\u2019s catch up soon!",
      time: "04:46",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "14",
      sender: "Ali Khan",
      text: "Please review the latest document.",
      time: "06:20",
      date: "2025-04-05",
    },
  ],
  "15": [
    {
      id: "1",
      chatId: "15",
      sender: "Sara Lee",
      text: "Please review the latest document.",
      time: "07:49",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "15",
      sender: "Jane Smith",
      text: "Hey there! Welcome to your inbox.",
      time: "06:29",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "15",
      sender: "Michael Chen",
      text: "Please review the latest document.",
      time: "06:18",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "15",
      sender: "Mary Hilda",
      text: "Hey there! Welcome to your inbox.",
      time: "05:35",
      date: "2025-04-05",
    },
  ],
  "16": [
    {
      id: "1",
      chatId: "16",
      sender: "Jane Smith",
      text: "Don't forget the deadline.",
      time: "07:39",
      date: "2025-04-05",
    },
  ],
  "17": [
    {
      id: "1",
      chatId: "17",
      sender: "Obaidullah",
      text: "Welcome aboard!",
      time: "05:58",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "17",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "06:58",
      date: "2025-04-05",
    },
  ],
  "18": [
    {
      id: "1",
      chatId: "18",
      sender: "Sara Lee",
      text: "Your profile is incomplete.",
      time: "06:44",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "18",
      sender: "John Doe",
      text: "Please review the latest document.",
      time: "06:56",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "18",
      sender: "Jane Smith",
      text: "Sure thing, Claren.",
      time: "06:45",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "18",
      sender: "John Doe",
      text: "Meeting starts at 10 AM.",
      time: "06:14",
      date: "2025-04-05",
    },
  ],
  "19": [
    {
      id: "1",
      chatId: "19",
      sender: "Ali Khan",
      text: "Meeting starts at 10 AM.",
      time: "05:31",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "19",
      sender: "Liam Patel",
      text: "Don't forget the deadline.",
      time: "04:12",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "19",
      sender: "Claren",
      text: "The file has been sent.",
      time: "05:00",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "19",
      sender: "Mary Hilda",
      text: "Don't forget the deadline.",
      time: "07:55",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "19",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "04:11",
      date: "2025-04-05",
    },
  ],
  "20": [
    {
      id: "1",
      chatId: "20",
      sender: "Jane Smith",
      text: "Sure thing, Claren.",
      time: "04:27",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "20",
      sender: "Michael Chen",
      text: "Meeting starts at 10 AM.",
      time: "07:41",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "20",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "04:39",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "20",
      sender: "Sara Lee",
      text: "Your profile is incomplete.",
      time: "05:20",
      date: "2025-04-05",
    },
  ],
  "21": [
    {
      id: "1",
      chatId: "21",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "03:09",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "21",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "05:51",
      date: "2025-04-05",
    },
  ],
  "22": [
    {
      id: "1",
      chatId: "22",
      sender: "Obaidullah",
      text: "Please review the latest document.",
      time: "06:57",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "22",
      sender: "Obaidullah",
      text: "Please review the latest document.",
      time: "06:44",
      date: "2025-04-05",
    },
  ],
  "23": [
    {
      id: "1",
      chatId: "23",
      sender: "Ali Khan",
      text: "Meeting starts at 10 AM.",
      time: "03:57",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "23",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "05:22",
      date: "2025-04-05",
    },
  ],
  "24": [
    {
      id: "1",
      chatId: "24",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "06:39",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "24",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "04:22",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "24",
      sender: "Obaidullah",
      text: "The file has been sent.",
      time: "07:07",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "24",
      sender: "Claren",
      text: "Don't forget the deadline.",
      time: "03:52",
      date: "2025-04-05",
    },
  ],
  "25": [
    {
      id: "1",
      chatId: "25",
      sender: "Mary Hilda",
      text: "Sure thing, Claren.",
      time: "05:15",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "25",
      sender: "Claren",
      text: "Please review the latest document.",
      time: "05:20",
      date: "2025-04-05",
    },
  ],
  "26": [
    {
      id: "1",
      chatId: "26",
      sender: "FastVisa Support",
      text: "Let\u2019s catch up soon!",
      time: "04:15",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "26",
      sender: "Mary Hilda",
      text: "Hey there! Welcome to your inbox.",
      time: "07:02",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "26",
      sender: "Michael Chen",
      text: "Your case has been updated.",
      time: "07:20",
      date: "2025-04-05",
    },
  ],
  "27": [
    {
      id: "1",
      chatId: "27",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "07:38",
      date: "2025-04-05",
    },
  ],
  "28": [
    {
      id: "1",
      chatId: "28",
      sender: "Liam Patel",
      text: "Welcome aboard!",
      time: "07:14",
      date: "2025-04-05",
    },
  ],
  "29": [
    {
      id: "1",
      chatId: "29",
      sender: "Liam Patel",
      text: "Sure thing, Claren.",
      time: "03:42",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "29",
      sender: "Obaidullah",
      text: "Don't forget the deadline.",
      time: "04:42",
      date: "2025-04-05",
    },
  ],
  "30": [
    {
      id: "1",
      chatId: "30",
      sender: "Claren",
      text: "Welcome aboard!",
      time: "04:29",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "30",
      sender: "Claren",
      text: "Meeting starts at 10 AM.",
      time: "04:19",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "30",
      sender: "Mary Hilda",
      text: "Let\u2019s catch up soon!",
      time: "07:05",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "30",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "04:11",
      date: "2025-04-05",
    },
  ],
  "31": [
    {
      id: "1",
      chatId: "31",
      sender: "Ali Khan",
      text: "Your case has been updated.",
      time: "06:09",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "31",
      sender: "Liam Patel",
      text: "Don't forget the deadline.",
      time: "05:08",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "31",
      sender: "Liam Patel",
      text: "Welcome aboard!",
      time: "03:40",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "31",
      sender: "Jane Smith",
      text: "Hey there! Welcome to your inbox.",
      time: "07:50",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "31",
      sender: "Obaidullah",
      text: "Welcome aboard!",
      time: "07:40",
      date: "2025-04-05",
    },
  ],
  "32": [
    {
      id: "1",
      chatId: "32",
      sender: "Jane Smith",
      text: "Meeting starts at 10 AM.",
      time: "05:10",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "32",
      sender: "Liam Patel",
      text: "The file has been sent.",
      time: "07:13",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "32",
      sender: "Mary Hilda",
      text: "Don't forget the deadline.",
      time: "07:06",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "32",
      sender: "Jane Smith",
      text: "Please review the latest document.",
      time: "05:07",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "32",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "07:42",
      date: "2025-04-05",
    },
  ],
  "33": [
    {
      id: "1",
      chatId: "33",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "05:57",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "33",
      sender: "Mary Hilda",
      text: "Let\u2019s catch up soon!",
      time: "06:37",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "33",
      sender: "Mary Hilda",
      text: "Let\u2019s catch up soon!",
      time: "03:08",
      date: "2025-04-05",
    },
  ],
  "34": [
    {
      id: "1",
      chatId: "34",
      sender: "Ali Khan",
      text: "Hey there! Welcome to your inbox.",
      time: "05:09",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "34",
      sender: "Ali Khan",
      text: "Your case has been updated.",
      time: "05:17",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "34",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "05:49",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "34",
      sender: "Liam Patel",
      text: "Meeting starts at 10 AM.",
      time: "06:30",
      date: "2025-04-05",
    },
  ],
  "35": [
    {
      id: "1",
      chatId: "35",
      sender: "Sara Lee",
      text: "Let\u2019s catch up soon!",
      time: "03:48",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "35",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "03:39",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "35",
      sender: "Jane Smith",
      text: "The file has been sent.",
      time: "05:23",
      date: "2025-04-05",
    },
  ],
  "36": [
    {
      id: "1",
      chatId: "36",
      sender: "Claren",
      text: "Please review the latest document.",
      time: "07:55",
      date: "2025-04-05",
    },
  ],
  "37": [
    {
      id: "1",
      chatId: "37",
      sender: "Jane Smith",
      text: "Please review the latest document.",
      time: "03:56",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "37",
      sender: "Obaidullah",
      text: "Let\u2019s catch up soon!",
      time: "06:43",
      date: "2025-04-05",
    },
  ],
  "38": [
    {
      id: "1",
      chatId: "38",
      sender: "Ali Khan",
      text: "Let\u2019s catch up soon!",
      time: "03:27",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "38",
      sender: "Obaidullah",
      text: "Your case has been updated.",
      time: "07:56",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "38",
      sender: "FastVisa Support",
      text: "The file has been sent.",
      time: "05:43",
      date: "2025-04-05",
    },
  ],
  "39": [
    {
      id: "1",
      chatId: "39",
      sender: "FastVisa Support",
      text: "Your profile is incomplete.",
      time: "06:51",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "39",
      sender: "FastVisa Support",
      text: "Hey there! Welcome to your inbox.",
      time: "07:33",
      date: "2025-04-05",
    },
  ],
  "40": [
    {
      id: "1",
      chatId: "40",
      sender: "Claren",
      text: "Don't forget the deadline.",
      time: "05:27",
      date: "2025-04-05",
    },
  ],
  "41": [
    {
      id: "1",
      chatId: "41",
      sender: "Ali Khan",
      text: "Let\u2019s catch up soon!",
      time: "05:39",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "41",
      sender: "John Doe",
      text: "Your profile is incomplete.",
      time: "05:08",
      date: "2025-04-05",
    },
  ],
  "42": [
    {
      id: "1",
      chatId: "42",
      sender: "Sara Lee",
      text: "Please review the latest document.",
      time: "05:34",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "42",
      sender: "Mary Hilda",
      text: "Sure thing, Claren.",
      time: "05:54",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "42",
      sender: "John Doe",
      text: "Your case has been updated.",
      time: "03:18",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "42",
      sender: "Jane Smith",
      text: "Your case has been updated.",
      time: "07:28",
      date: "2025-04-05",
    },
  ],
  "43": [
    {
      id: "1",
      chatId: "43",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "05:14",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "43",
      sender: "FastVisa Support",
      text: "Meeting starts at 10 AM.",
      time: "03:46",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "43",
      sender: "John Doe",
      text: "Sure thing, Claren.",
      time: "06:28",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "43",
      sender: "FastVisa Support",
      text: "Let\u2019s catch up soon!",
      time: "05:54",
      date: "2025-04-05",
    },
  ],
  "44": [
    {
      id: "1",
      chatId: "44",
      sender: "Jane Smith",
      text: "Meeting starts at 10 AM.",
      time: "03:53",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "44",
      sender: "FastVisa Support",
      text: "Don't forget the deadline.",
      time: "07:34",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "44",
      sender: "Ali Khan",
      text: "Let\u2019s catch up soon!",
      time: "05:05",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "44",
      sender: "Michael Chen",
      text: "Your profile is incomplete.",
      time: "04:51",
      date: "2025-04-05",
    },
  ],
  "45": [
    {
      id: "1",
      chatId: "45",
      sender: "Liam Patel",
      text: "The file has been sent.",
      time: "07:12",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "45",
      sender: "Mary Hilda",
      text: "Your case has been updated.",
      time: "06:11",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "45",
      sender: "Obaidullah",
      text: "Please review the latest document.",
      time: "06:32",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "45",
      sender: "Claren",
      text: "The file has been sent.",
      time: "03:44",
      date: "2025-04-05",
    },
  ],
  "46": [
    {
      id: "1",
      chatId: "46",
      sender: "John Doe",
      text: "Sure thing, Claren.",
      time: "03:56",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "46",
      sender: "Liam Patel",
      text: "Don't forget the deadline.",
      time: "05:32",
      date: "2025-04-05",
    },
  ],
  "47": [
    {
      id: "1",
      chatId: "47",
      sender: "Michael Chen",
      text: "Let\u2019s catch up soon!",
      time: "05:44",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "47",
      sender: "John Doe",
      text: "Don't forget the deadline.",
      time: "03:37",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "47",
      sender: "Liam Patel",
      text: "Sure thing, Claren.",
      time: "03:22",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "47",
      sender: "Sara Lee",
      text: "Let\u2019s catch up soon!",
      time: "05:03",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "47",
      sender: "Michael Chen",
      text: "Hey there! Welcome to your inbox.",
      time: "03:04",
      date: "2025-04-05",
    },
  ],
  "48": [
    {
      id: "1",
      chatId: "48",
      sender: "Sara Lee",
      text: "Don't forget the deadline.",
      time: "03:32",
      date: "2025-04-05",
    },
  ],
  "49": [
    {
      id: "1",
      chatId: "49",
      sender: "Claren",
      text: "Your profile is incomplete.",
      time: "03:43",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "49",
      sender: "Ali Khan",
      text: "Meeting starts at 10 AM.",
      time: "05:24",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "49",
      sender: "Michael Chen",
      text: "Let\u2019s catch up soon!",
      time: "07:20",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "49",
      sender: "Jane Smith",
      text: "Meeting starts at 10 AM.",
      time: "07:54",
      date: "2025-04-05",
    },
  ],
  "50": [
    {
      id: "1",
      chatId: "50",
      sender: "Michael Chen",
      text: "The file has been sent.",
      time: "07:39",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "50",
      sender: "Ali Khan",
      text: "Let\u2019s catch up soon!",
      time: "05:06",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "50",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "05:37",
      date: "2025-04-05",
    },
  ],
  "51": [
    {
      id: "1",
      chatId: "51",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "05:09",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "51",
      sender: "John Doe",
      text: "The file has been sent.",
      time: "07:26",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "51",
      sender: "Mary Hilda",
      text: "Meeting starts at 10 AM.",
      time: "04:52",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "51",
      sender: "Michael Chen",
      text: "Don't forget the deadline.",
      time: "07:27",
      date: "2025-04-05",
    },
  ],
  "52": [
    {
      id: "1",
      chatId: "52",
      sender: "Sara Lee",
      text: "The file has been sent.",
      time: "04:08",
      date: "2025-04-05",
    },
  ],
  "53": [
    {
      id: "1",
      chatId: "53",
      sender: "FastVisa Support",
      text: "Let\u2019s catch up soon!",
      time: "05:13",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "53",
      sender: "Michael Chen",
      text: "Your case has been updated.",
      time: "04:34",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "53",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "04:31",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "53",
      sender: "John Doe",
      text: "Meeting starts at 10 AM.",
      time: "07:26",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "53",
      sender: "Ali Khan",
      text: "Welcome aboard!",
      time: "05:52",
      date: "2025-04-05",
    },
  ],
  "54": [
    {
      id: "1",
      chatId: "54",
      sender: "Mary Hilda",
      text: "Meeting starts at 10 AM.",
      time: "06:42",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "54",
      sender: "Jane Smith",
      text: "Your case has been updated.",
      time: "07:07",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "54",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "07:25",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "54",
      sender: "Claren",
      text: "Don't forget the deadline.",
      time: "04:24",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "54",
      sender: "Michael Chen",
      text: "Let\u2019s catch up soon!",
      time: "03:11",
      date: "2025-04-05",
    },
  ],
  "55": [
    {
      id: "1",
      chatId: "55",
      sender: "John Doe",
      text: "Meeting starts at 10 AM.",
      time: "07:46",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "55",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "03:58",
      date: "2025-04-05",
    },
  ],
  "56": [
    {
      id: "1",
      chatId: "56",
      sender: "Ali Khan",
      text: "Don't forget the deadline.",
      time: "06:33",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "56",
      sender: "Liam Patel",
      text: "Meeting starts at 10 AM.",
      time: "04:08",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "56",
      sender: "Mary Hilda",
      text: "Please review the latest document.",
      time: "06:14",
      date: "2025-04-05",
    },
  ],
  "57": [
    {
      id: "1",
      chatId: "57",
      sender: "Ali Khan",
      text: "Please review the latest document.",
      time: "03:21",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "57",
      sender: "FastVisa Support",
      text: "Your profile is incomplete.",
      time: "07:49",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "57",
      sender: "Mary Hilda",
      text: "Please review the latest document.",
      time: "03:39",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "57",
      sender: "Claren",
      text: "Meeting starts at 10 AM.",
      time: "05:55",
      date: "2025-04-05",
    },
  ],
  "58": [
    {
      id: "1",
      chatId: "58",
      sender: "Michael Chen",
      text: "Don't forget the deadline.",
      time: "05:21",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "58",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "04:29",
      date: "2025-04-05",
    },
  ],
  "59": [
    {
      id: "1",
      chatId: "59",
      sender: "Liam Patel",
      text: "Your case has been updated.",
      time: "04:44",
      date: "2025-04-05",
    },
  ],
  "60": [
    {
      id: "1",
      chatId: "60",
      sender: "John Doe",
      text: "Your case has been updated.",
      time: "04:13",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "60",
      sender: "Ali Khan",
      text: "Don't forget the deadline.",
      time: "03:03",
      date: "2025-04-05",
    },
  ],
  "61": [
    {
      id: "1",
      chatId: "61",
      sender: "Michael Chen",
      text: "Please review the latest document.",
      time: "04:12",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "61",
      sender: "FastVisa Support",
      text: "Your profile is incomplete.",
      time: "07:12",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "61",
      sender: "Claren",
      text: "Please review the latest document.",
      time: "07:42",
      date: "2025-04-05",
    },
  ],
  "62": [
    {
      id: "1",
      chatId: "62",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "07:55",
      date: "2025-04-05",
    },
  ],
  "63": [
    {
      id: "1",
      chatId: "63",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "05:00",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "63",
      sender: "Liam Patel",
      text: "Don't forget the deadline.",
      time: "03:52",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "63",
      sender: "John Doe",
      text: "Please review the latest document.",
      time: "06:03",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "63",
      sender: "John Doe",
      text: "Let\u2019s catch up soon!",
      time: "06:23",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "63",
      sender: "Obaidullah",
      text: "Meeting starts at 10 AM.",
      time: "06:31",
      date: "2025-04-05",
    },
  ],
  "64": [
    {
      id: "1",
      chatId: "64",
      sender: "Obaidullah",
      text: "Sure thing, Claren.",
      time: "07:11",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "64",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "03:52",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "64",
      sender: "Jane Smith",
      text: "The file has been sent.",
      time: "07:51",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "64",
      sender: "Claren",
      text: "Sure thing, Claren.",
      time: "03:38",
      date: "2025-04-05",
    },
  ],
  "65": [
    {
      id: "1",
      chatId: "65",
      sender: "Liam Patel",
      text: "Your profile is incomplete.",
      time: "05:06",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "65",
      sender: "Jane Smith",
      text: "Don't forget the deadline.",
      time: "07:19",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "65",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "03:57",
      date: "2025-04-05",
    },
  ],
  "66": [
    {
      id: "1",
      chatId: "66",
      sender: "Liam Patel",
      text: "Hey there! Welcome to your inbox.",
      time: "03:51",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "66",
      sender: "FastVisa Support",
      text: "The file has been sent.",
      time: "07:26",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "66",
      sender: "Michael Chen",
      text: "Let\u2019s catch up soon!",
      time: "05:32",
      date: "2025-04-05",
    },
  ],
  "67": [
    {
      id: "1",
      chatId: "67",
      sender: "FastVisa Support",
      text: "Sure thing, Claren.",
      time: "03:57",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "67",
      sender: "Ali Khan",
      text: "Please review the latest document.",
      time: "03:20",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "67",
      sender: "Mary Hilda",
      text: "Welcome aboard!",
      time: "07:07",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "67",
      sender: "Jane Smith",
      text: "Let\u2019s catch up soon!",
      time: "07:25",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "67",
      sender: "Mary Hilda",
      text: "Your case has been updated.",
      time: "03:45",
      date: "2025-04-05",
    },
  ],
  "68": [
    {
      id: "1",
      chatId: "68",
      sender: "Jane Smith",
      text: "Welcome aboard!",
      time: "07:58",
      date: "2025-04-05",
    },
  ],
  "69": [
    {
      id: "1",
      chatId: "69",
      sender: "Michael Chen",
      text: "Hey there! Welcome to your inbox.",
      time: "07:35",
      date: "2025-04-05",
    },
  ],
  "70": [
    {
      id: "1",
      chatId: "70",
      sender: "Obaidullah",
      text: "Your case has been updated.",
      time: "03:16",
      date: "2025-04-05",
    },
  ],
  "71": [
    {
      id: "1",
      chatId: "71",
      sender: "John Doe",
      text: "Don't forget the deadline.",
      time: "03:03",
      date: "2025-04-05",
    },
  ],
  "72": [
    {
      id: "1",
      chatId: "72",
      sender: "FastVisa Support",
      text: "Your case has been updated.",
      time: "07:06",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "72",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "06:27",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "72",
      sender: "Jane Smith",
      text: "The file has been sent.",
      time: "06:06",
      date: "2025-04-05",
    },
  ],
  "73": [
    {
      id: "1",
      chatId: "73",
      sender: "Mary Hilda",
      text: "Please review the latest document.",
      time: "04:37",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "73",
      sender: "FastVisa Support",
      text: "Sure thing, Claren.",
      time: "06:32",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "73",
      sender: "John Doe",
      text: "The file has been sent.",
      time: "07:27",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "73",
      sender: "Ali Khan",
      text: "Sure thing, Claren.",
      time: "03:46",
      date: "2025-04-05",
    },
  ],
  "74": [
    {
      id: "1",
      chatId: "74",
      sender: "Mary Hilda",
      text: "Sure thing, Claren.",
      time: "04:00",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "74",
      sender: "Ali Khan",
      text: "Your profile is incomplete.",
      time: "03:23",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "74",
      sender: "Ali Khan",
      text: "Please review the latest document.",
      time: "03:21",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "74",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "05:30",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "74",
      sender: "Mary Hilda",
      text: "Don't forget the deadline.",
      time: "07:36",
      date: "2025-04-05",
    },
  ],
  "75": [
    {
      id: "1",
      chatId: "75",
      sender: "FastVisa Support",
      text: "Hey there! Welcome to your inbox.",
      time: "07:44",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "75",
      sender: "John Doe",
      text: "Don't forget the deadline.",
      time: "04:54",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "75",
      sender: "Liam Patel",
      text: "Your profile is incomplete.",
      time: "03:32",
      date: "2025-04-05",
    },
  ],
  "76": [
    {
      id: "1",
      chatId: "76",
      sender: "Jane Smith",
      text: "Hey there! Welcome to your inbox.",
      time: "07:23",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "76",
      sender: "Ali Khan",
      text: "Your case has been updated.",
      time: "04:41",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "76",
      sender: "Obaidullah",
      text: "Meeting starts at 10 AM.",
      time: "04:13",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "76",
      sender: "Ali Khan",
      text: "Meeting starts at 10 AM.",
      time: "05:04",
      date: "2025-04-05",
    },
  ],
  "77": [
    {
      id: "1",
      chatId: "77",
      sender: "Obaidullah",
      text: "Don't forget the deadline.",
      time: "03:48",
      date: "2025-04-05",
    },
  ],
  "78": [
    {
      id: "1",
      chatId: "78",
      sender: "Michael Chen",
      text: "Meeting starts at 10 AM.",
      time: "07:21",
      date: "2025-04-05",
    },
  ],
  "79": [
    {
      id: "1",
      chatId: "79",
      sender: "Jane Smith",
      text: "Your case has been updated.",
      time: "03:14",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "79",
      sender: "Liam Patel",
      text: "Your case has been updated.",
      time: "04:48",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "79",
      sender: "Claren",
      text: "Hey there! Welcome to your inbox.",
      time: "04:54",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "79",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "07:56",
      date: "2025-04-05",
    },
  ],
  "80": [
    {
      id: "1",
      chatId: "80",
      sender: "Obaidullah",
      text: "Meeting starts at 10 AM.",
      time: "03:47",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "80",
      sender: "Jane Smith",
      text: "Your case has been updated.",
      time: "03:44",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "80",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "05:28",
      date: "2025-04-05",
    },
  ],
  "81": [
    {
      id: "1",
      chatId: "81",
      sender: "Sara Lee",
      text: "The file has been sent.",
      time: "06:04",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "81",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "04:18",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "81",
      sender: "Michael Chen",
      text: "Your case has been updated.",
      time: "03:58",
      date: "2025-04-05",
    },
  ],
  "82": [
    {
      id: "1",
      chatId: "82",
      sender: "Obaidullah",
      text: "Welcome aboard!",
      time: "06:27",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "82",
      sender: "Liam Patel",
      text: "Your profile is incomplete.",
      time: "07:04",
      date: "2025-04-05",
    },
  ],
  "83": [
    {
      id: "1",
      chatId: "83",
      sender: "FastVisa Support",
      text: "Please review the latest document.",
      time: "05:03",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "83",
      sender: "Mary Hilda",
      text: "Sure thing, Claren.",
      time: "05:01",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "83",
      sender: "Mary Hilda",
      text: "Your case has been updated.",
      time: "04:50",
      date: "2025-04-05",
    },
  ],
  "84": [
    {
      id: "1",
      chatId: "84",
      sender: "Jane Smith",
      text: "Let\u2019s catch up soon!",
      time: "03:48",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "84",
      sender: "Ali Khan",
      text: "Sure thing, Claren.",
      time: "05:32",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "84",
      sender: "Michael Chen",
      text: "The file has been sent.",
      time: "03:16",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "84",
      sender: "Mary Hilda",
      text: "Don't forget the deadline.",
      time: "07:35",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "84",
      sender: "Jane Smith",
      text: "Meeting starts at 10 AM.",
      time: "06:50",
      date: "2025-04-05",
    },
  ],
  "85": [
    {
      id: "1",
      chatId: "85",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "04:13",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "85",
      sender: "Claren",
      text: "Meeting starts at 10 AM.",
      time: "07:31",
      date: "2025-04-05",
    },
  ],
  "86": [
    {
      id: "1",
      chatId: "86",
      sender: "Claren",
      text: "Your profile is incomplete.",
      time: "03:49",
      date: "2025-04-05",
    },
  ],
  "87": [
    {
      id: "1",
      chatId: "87",
      sender: "Michael Chen",
      text: "Sure thing, Claren.",
      time: "05:03",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "87",
      sender: "FastVisa Support",
      text: "Meeting starts at 10 AM.",
      time: "07:07",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "87",
      sender: "Michael Chen",
      text: "Hey there! Welcome to your inbox.",
      time: "06:26",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "87",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "05:21",
      date: "2025-04-05",
    },
  ],
  "88": [
    {
      id: "1",
      chatId: "88",
      sender: "Sara Lee",
      text: "Your profile is incomplete.",
      time: "05:40",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "88",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "07:58",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "88",
      sender: "Liam Patel",
      text: "Meeting starts at 10 AM.",
      time: "05:39",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "88",
      sender: "Jane Smith",
      text: "Let\u2019s catch up soon!",
      time: "07:34",
      date: "2025-04-05",
    },
  ],
  "89": [
    {
      id: "1",
      chatId: "89",
      sender: "Claren",
      text: "Don't forget the deadline.",
      time: "07:32",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "89",
      sender: "Obaidullah",
      text: "Please review the latest document.",
      time: "07:46",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "89",
      sender: "FastVisa Support",
      text: "Sure thing, Claren.",
      time: "07:45",
      date: "2025-04-05",
    },
  ],
  "90": [
    {
      id: "1",
      chatId: "90",
      sender: "Sara Lee",
      text: "Sure thing, Claren.",
      time: "07:27",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "90",
      sender: "Sara Lee",
      text: "Hey there! Welcome to your inbox.",
      time: "06:42",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "90",
      sender: "Liam Patel",
      text: "Hey there! Welcome to your inbox.",
      time: "03:25",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "90",
      sender: "FastVisa Support",
      text: "Welcome aboard!",
      time: "06:18",
      date: "2025-04-05",
    },
  ],
  "91": [
    {
      id: "1",
      chatId: "91",
      sender: "Obaidullah",
      text: "Meeting starts at 10 AM.",
      time: "04:23",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "91",
      sender: "Sara Lee",
      text: "The file has been sent.",
      time: "03:29",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "91",
      sender: "Michael Chen",
      text: "Don't forget the deadline.",
      time: "04:03",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "91",
      sender: "Claren",
      text: "Don't forget the deadline.",
      time: "07:07",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "91",
      sender: "FastVisa Support",
      text: "Let\u2019s catch up soon!",
      time: "06:43",
      date: "2025-04-05",
    },
  ],
  "92": [
    {
      id: "1",
      chatId: "92",
      sender: "Michael Chen",
      text: "Hey there! Welcome to your inbox.",
      time: "03:43",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "92",
      sender: "Liam Patel",
      text: "Let\u2019s catch up soon!",
      time: "07:21",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "92",
      sender: "FastVisa Support",
      text: "Your profile is incomplete.",
      time: "04:05",
      date: "2025-04-05",
    },
  ],
  "93": [
    {
      id: "1",
      chatId: "93",
      sender: "Jane Smith",
      text: "Your profile is incomplete.",
      time: "06:35",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "93",
      sender: "Jane Smith",
      text: "The file has been sent.",
      time: "05:44",
      date: "2025-04-05",
    },
  ],
  "94": [
    {
      id: "1",
      chatId: "94",
      sender: "Liam Patel",
      text: "The file has been sent.",
      time: "07:46",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "94",
      sender: "Sara Lee",
      text: "The file has been sent.",
      time: "07:00",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "94",
      sender: "Michael Chen",
      text: "The file has been sent.",
      time: "03:15",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "94",
      sender: "Obaidullah",
      text: "Meeting starts at 10 AM.",
      time: "04:32",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "94",
      sender: "John Doe",
      text: "Let\u2019s catch up soon!",
      time: "03:36",
      date: "2025-04-05",
    },
  ],
  "95": [
    {
      id: "1",
      chatId: "95",
      sender: "Michael Chen",
      text: "Your profile is incomplete.",
      time: "06:29",
      date: "2025-04-05",
    },
  ],
  "96": [
    {
      id: "1",
      chatId: "96",
      sender: "John Doe",
      text: "Welcome aboard!",
      time: "07:54",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "96",
      sender: "John Doe",
      text: "The file has been sent.",
      time: "03:32",
      date: "2025-04-05",
    },
  ],
  "97": [
    {
      id: "1",
      chatId: "97",
      sender: "Michael Chen",
      text: "Please review the latest document.",
      time: "04:29",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "97",
      sender: "FastVisa Support",
      text: "The file has been sent.",
      time: "03:15",
      date: "2025-04-05",
    },
  ],
  "98": [
    {
      id: "1",
      chatId: "98",
      sender: "Michael Chen",
      text: "Welcome aboard!",
      time: "05:55",
      date: "2025-04-05",
    },
  ],
  "99": [
    {
      id: "1",
      chatId: "99",
      sender: "Michael Chen",
      text: "Don't forget the deadline.",
      time: "05:47",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "99",
      sender: "Ali Khan",
      text: "The file has been sent.",
      time: "04:18",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "99",
      sender: "Obaidullah",
      text: "Let\u2019s catch up soon!",
      time: "06:38",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "99",
      sender: "Obaidullah",
      text: "The file has been sent.",
      time: "06:37",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "99",
      sender: "Ali Khan",
      text: "Sure thing, Claren.",
      time: "04:00",
      date: "2025-04-05",
    },
  ],
  "100": [
    {
      id: "1",
      chatId: "100",
      sender: "Ali Khan",
      text: "Let\u2019s catch up soon!",
      time: "03:19",
      date: "2025-04-05",
    },
    {
      id: "2",
      chatId: "100",
      sender: "Ali Khan",
      text: "Hey there! Welcome to your inbox.",
      time: "05:21",
      date: "2025-04-05",
    },
    {
      id: "3",
      chatId: "100",
      sender: "Sara Lee",
      text: "Meeting starts at 10 AM.",
      time: "03:13",
      date: "2025-04-05",
    },
    {
      id: "4",
      chatId: "100",
      sender: "John Doe",
      text: "Sure thing, Claren.",
      time: "03:33",
      date: "2025-04-05",
    },
    {
      id: "5",
      chatId: "100",
      sender: "Sara Lee",
      text: "Hey there! Welcome to your inbox.",
      time: "04:01",
      date: "2025-04-05",
    },
  ],
};
